Update caddy & geth
asobicoin/geth-private-network pull request #1
Opened 2019-03-20 10:04 UTC by shunsukehondo

2019-03-20 10:05 UTC, shunsukehondo commented on roles/caddy/templates/Caddyfile
> +    }
todo optional

2019-03-20 10:05 UTC, shunsukehondo commented on roles/caddy/vars/main.yml
> +caddy_url: https://caddyserver.com/download/linux/amd64?plugins=tls.dns.digitalocean&license=personal&telemetry=off
todo optional

2019-03-22 03:10 UTC, shunsukehondo commented on roles/geth/templates/genesis.json
> +    "0000000000000000000000000000000000000000": {
precompiled contracts
https://solidity.readthedocs.io/en/latest/units-and-global-variables.html#mathematical-and-cryptographic-functions

2019-04-01 05:13 UTC, justuswilhelm requested changes

2019-04-01 05:13 UTC, justuswilhelm commented on README.md
> +letsenrtypt_staging=false
```suggestion
letsencrypt_staging=false
```

2019-04-01 05:13 UTC, justuswilhelm commented on roles/caddy/templates/caddy.service
> +
```suggestion
```

2019-04-01 05:13 UTC, justuswilhelm commented on roles/geth/templates/genesis.json
> +        "homesteadBlock": 1,
I think if we apply this update to our private chain, it will become invalid :/

2019-04-01 05:13 UTC, justuswilhelm commented on roles/geth/templates/genesis.json
> -    "coinbase": "0x0000000000000000000000000000000000000000",
Sorry, could you revert the order here to match the original one? It will make the diff a bit easier to read.

2019-04-01 06:58 UTC, shunsukehondo commented on README.md
> +letsenrtypt_staging=false
😨

2019-04-01 06:58 UTC, shunsukehondo commented on roles/caddy/templates/caddy.service
> +
jinja2 removes newline after if tag

2019-04-01 09:39 UTC, justuswilhelm approved these changes
Beautiful. Thanks.

2019-04-01 09:39 UTC, merged